### ISSUE TITLE
No funciona desde el cambio de dominio

### ISSUE THREAD

**Issue by fallosistema** [santos82/LFS201#3]
El join.py no funciona, genera un archivo vacio. En la extensión he modificado el dominio y funciona, el clean también, pero el join no suelta ningún error y parece más complejo de editar.

Salu2

**Comment by s-nt-s** [comment]
Hola

Ya no tengo acceso a los cursos, así que no se como es la nueva plataforma ni que es lo que ha cambiado.

Pero este fork https://github.com/kanner/lfs-crawler se supone que funciona actualmente (eso sí, con la versión inglesa). Quizá mirando los cambios que han hecho ahí puedas ver que cambios necesitas hacer tu.

Yo solo puedo decirte que quiza el problema este aquí: https://github.com/s-nt-s/LFS201/blob/master/join.py#L188 , es el for principal, si ese find no encuentra nada seria normal que generara un html vació.

Un saludo.

P.D.: Si das con ello te animo a hacer un fork de este proyecto y subir los cambios en él para que otras personas puedan usarlo.
